### ISSUE TITLE
Add mission statement to website

### ISSUE THREAD

**Issue by tolu** [elateas/elateas-website#11]
But first we need a good translation in english

> Vi skal skape en trygg plattform for felleskap, involvering og kontinuerlig fornyelse, slik at vi  tilrettelegger for individer som påvirker konsulentbransjen og den teknologiske videreutviklingen av Norge positivt.

Google translate gets us on the path but the grammar is not all that jazz

> We will create a safe platform for community, involvement and continuous renewal, so that we facilitate individuals who influence the consulting industry and the technological development of Norway.

One idea below 
> We aim to create a solid platform for community, involvement and continuous renewal, so that we facilitate for individuals who positively influence the consulting industry and the technological revolution in Norway.

**Comment by frdrks** [comment]
Added in #19. It is now in Norwegian, so no translation is needed
